config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
     sessions: 'users/sessions',
     registrations: 'users/registrations',
     :omniauth_callbacks => "users/omniauth_callbacks"
   }
   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self)
   resources :users do
     resources :appointments, except: :index
   end
  resources :appointments, only: :index
  get 'geocontroller/findaddress'
  root to: 'users#index'
  get 'professional/index'
  get 'about/about_us'
  delete '/users/:user_id/appointments/:id', to: 'appointments#destroy', as: 'destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
  enum role: [:Admin, :Cliente, :Profesional]
  mount_uploader :photo, ImageUploader
  has_many :client_appointments, class_name: 'Appointment', foreign_key: :client_id, dependent: :destroy
  has_many :professional_appointments, class_name: 'Appointment', foreign_key: :professional_id, dependent: :destroy
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end
  def self.created_by_day
    group_by_day(:created_at).count
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]
  def facebook
   # Debemos crear el método .from_omniauth en nuestro modelo User (app/models/user.rb)
   @user = User.from_omniauth(request.env["omniauth.auth"])
   if @user.persisted?
   sign_in_and_redirect @user
   set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
   else
   redirect_to root_path, notice: 'Error al iniciar sesión con Facebook.'
   end
  end
  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @roles = User.roles.except('Admin').keys.to_a
    super
  end

  # POST /resource
   def create
     @roles = User.roles.except('Admin').keys.to_a
     super
   end

  # GET /resource/edit
  def edit
    @roles = User.roles.except('Admin').keys.to_a
    super
  end

  # PUT /resource
  def update
    @roles = User.roles.except('Admin').keys.to_a
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo email ocupation phone role address
     latitude longitude])
   end

   def update_resource(resource, configure_permitted_parameters)
   resource.update_without_password(configure_permitted_parameters)
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @user = User.where(role: 2).last(3)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit;end
  private

  def user_params
    params.require(:user).permit(:name, :photo, :email, :phone, :ocupation, :role, :created_at)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="templatemo_headerimage">
  <div class="flexslider">
    <ul class="slides">
      <li>
        <img src="<%= asset_path '1.jpg' %>" alt="Slide 1">
        <div class="slider-caption">
        <div class="templatemo_homewrapper">
          <h1 class="wow fadeInDown" data-wow-delay="2000">ENCUENTRA TU SOLUCIÓN</h1>
          <h2 class="wow fadeInDown" data-wow-delay="2000">
        <span>BUSCA &AMP; RESUELVE TUS PROBLEMAS </span>
      </h2>
      <%= link_to "REGISTRATE EN NUESTRO SITIO", new_user_registration_path, class:'smoothScroll btn btn-default wow fadeInDown' %>
        </div>
      </div>
      </li>
      <li>
        <img src="<%= asset_path 'slider/2.jpg'%>" alt="">
        <div class="slider-caption">
        <div class="templatemo_homewrapper">
          <h1 class="wow fadeInDown" data-wow-delay="2000">Flex Slider, CSS Flexbox</h1>
          <h2 class="wow fadeInDown" data-wow-delay="2000">
        <span>work on all modern browsers, Works on IE 10+</span>
      </h2>
      <p>see caniuse.com for browser compatibility information</p>
      <a href="#about" class="smoothScroll btn btn-default wow fadeInDown" data-wow-delay="2000">See about us</a>
        </div>
      </div>
      </li>
    </ul>
  </div>
</div>

<div id="service">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-4">
        <div class="media">
          <div class="media-object media-left wow fadeIn" data-wow-delay="0.1s">
            <i class="fab fa-accessible-icon"></i>
          </div>
          <div class="media-body wow fadeIn">
            <h3 class="media-heading">Un Sitio Para Todos</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt. </p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="media">
          <div class="media-object media-left wow fadeIn" data-wow-delay="0.3s">
            <i class="fas fa-address-card"></i>
          </div>
          <div class="media-body wow fadeIn">
            <h3 class="media-heading">Presentate a tus clientes</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="media">
          <div class="media-object media-left wow fadeIn" data-wow-delay="0.6s">
            <i class="fas fa-user-shield"></i>
          </div>
          <div class="media-body wow fadeIn" data-wow-delay="0.3s">
            <h3 class="media-heading">Sin Estafas</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="media">
          <div class="media-object media-left wow fadeIn" data-wow-delay="0.9s">
            <i class="fas fa-users"></i>
          </div>
          <div class="media-body wow fadeIn" data-wow-delay="0.6s">
            <h3 class="media-heading">Red de Profesionales</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="media">
          <div class="media-object media-left wow fadeIn" data-wow-delay="0.4s">
            <i class="fas fa-blind"></i>
          </div>
          <div class="media-body wow fadeIn" data-wow-delay="0.3s">
            <h3 class="media-heading">No más a ciegas</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-4">
        <div class="media">
          <div class="media-object media-left wow fadeIn" data-wow-delay="0.8s">
            <i class="fas fa-award"></i>
          </div>
          <div class="media-body wow fadeIn" data-wow-delay="0.6s">
            <h3 class="media-heading">Evalua el trabajo</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="divider">
  <div class="container">
    <div class="row">
      <div class="col-md-1 col-sm-1"></div>
      <div class="col-md-8 col-sm-8">
        <h2 class="wow bounce">We provide <strong>solutions</strong></h2>
        <h3 class="wow fadeIn" data-wow-delay="0.6s"><mark>Creative</mark> Designers &amp; <mark>Talented</mark> Developers</h3>
        <p class="wow fadeInUp" data-wow-delay="0.9s">Nulla ultricies bibendum augue et molestie. Suspendisse pellentesque mollis imperdiet. Quisque sodales laoreet tincidunt. Phasellus ut mi orci. Vivamus id odio ac justo tincidunt placerat. Nulla facilisi. Vivamus et dolor urna. Sed vestibulum urna justo, nec malesuada urna aliquet et.</p>
      </div>
      <div class="col-md-2 col-sm-2"></div>
    </div>
  </div>
</div>

<div id="team">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounce">Algunos de Nuestros Profesionales</h2>
      </div>
      <% @user.each do |u|%>
      <div class="col-md-4 col-sm-4 wow fadeIn" data-wow-delay="1.3s">
        <img src="<%= asset_path u.photo%>" class="img-responsive" alt="team img">
        <h4><%= u.role %></h4>
        <h3><%= u.name %></h3>
        <h2><%= u.email%></h2>
        <h2><%= u.ocupation %></h2>
         <ul class="text-center">
               <li><%= link_to "Ver Perfil", user_path(u.id), class:'smoothScroll btn btn-success wow fadeInUp' %></li>
         </ul>
      </div>
         <% end %>
    </div>
  </div>
</div>

<div id="contact">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 wow fadeInLeft" data-wow-delay="0.6s">
        <h2><strong>Solution</strong> Co.</h2>
        <p>Quisque at elit sapien. Sed velit enim, fringilla non suscipit quis, tristique et turpis. Proin vitae nisi justo.</p>
        <ul class="social-icon">
          <li><a href="#" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="#" class="fa fa-instagram"></a></li>
        </ul>
      </div>
      <div class="col-md-6 col-sm-7 wow fadeIn" data-wow-delay="0.9s">
        <address>
          <h3>Visit Office</h3>
          <p><i class="fa fa-map-marker too-icon"></i> 123 Walking Street, New York</p>
          <p><i class="fa fa-phone too-icon"></i> 010-010-0220</p>
          <p><i class="fa fa-envelope-o too-icon"></i> hello@company.com</p>
        </address>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div id="team">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounce"><%= @user.name %></h2>
      </div>
      <% Array(@user).each do |u|%>
      <div class="col-md-12 col-sm-12 wow fadeIn" data-wow-delay="1.3s">
        <img src="<%= asset_path u.photo%>" class="img-responsive" alt="team img">
        <h4><%= u.role %></h4>
        <h3><%= u.name %></h3>
        <h2><%= u.email%></h2>
        <%= link_to "Crear Cita", new_user_appointment_path(u.id), class: 'smoothScroll btn btn-success wow fadeInUp' %>
        <%= link_to "Volver", root_path, class: 'smoothScroll btn btn-success wow fadeInUp' %>
      </div>
         <% end %>
    </div>
  </div>
</div>