config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
     sessions: 'users/sessions',
     registrations: 'users/registrations',
     :omniauth_callbacks => "users/omniauth_callbacks"
   }
   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self)
   resources :users do
     resources :appointments, except: :index
   end
  resources :appointments, only: :index
  get 'geocontroller/findaddress'
  root to: 'users#index'
  get 'professional/index'
  get 'about/about_us'
  delete '/users/:user_id/appointments/:id', to: 'appointments#destroy', as: 'destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :client, class_name: 'User'
  belongs_to :professional, class_name: 'User'
  has_many :payments
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  attr_accessor
  def index
    if current_user.role == 'Profesional'
      @appointments = Appointment.all.where(professional_id: current_user.id)
    elsif current_user.role == 'Cliente'
      @appointments = Appointment.all.where(client_id: current_user.id)
    end

  end

  def show
    @appointment = Appointment.find(params[:id])
    @professional = User.find(params[:user_id])
  end

  def new
    @appointment = Appointment.new
    @user = User.find(params[:user_id])
  end

  def create
    @appointment = Appointment.new(appointments_params)
    @appointment.client_id = current_user.id
    @appointment.professional_id = User.find(params[:user_id]).id

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to user_appointment_path(params[:user_id], @appointment.id), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @appointment.update(appointments_params)
        format.html { redirect_to @appointment, notice: 'Event was successfully updated.'}
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @appointments = Appointment.find(params[:id])
    @appointments.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def appointments_params
    params.require(:appointment).permit(:description, :date, :user_id, :name)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<div class="container py-5">
<div class="row">
<div class="col-lg-8 mx-auto">
<%= form_with(model: [@user,Appointment.new], local: true) do |form|%>

<div class="form-group">
  <%= form.label :name, "Titulo Descriptivo" %>
  <%= form.text_field :name, class: 'form-control' %>
</div>


<div class="form-group">
  <%= form.label :description, "Descripción" %>
  <%= form.text_area :description, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :date, "Fecha" %>
  <%= form.date_select :date, class: 'form-control' %>
</div>

<div class="actions">
  <%= form.submit%>
</div>
<% end %>
</div>
</div>
</div>
dhkjdshkdhdashdaskhjdashkdsahdaskdashdashasdkjadskjdashdasjkhadshkdashads

app/views/appointments/index.html.erb
<div id="team">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow bounce">Tus Citas</h2>
      </div>
      <% @appointments.each do |app|%>
      <div class="col-md-6 col-sm-6 wow fadeIn" data-wow-delay="1.3s">
        <img src="<%= asset_path app.professional.photo%>" class="img-responsive" alt="<%= app.professional.name %>">
        <h4><%= app.professional.name%> </h4>
        <h4><%= app.name %></h4>
        <h3><%= app.date %></h3>
        <h2><%= app.description%></h2>
               <%= link_to "Volver", root_path, class:'smoothScroll btn btn-success wow fadeInUp' %>
               <%= link_to "Detalles", user_appointment_path(current_user, app),class:'smoothScroll btn btn-primary wow fadeInUp' %>
               <%= link_to 'Delete', destroy_path(app.professional.id, app), method: :delete, class: "btn btn-danger btn-sm" %>
      </div>
         <% end %>
    </div>
  </div>
</div>

app/views/appointments/new.html.erb
<div style = "padding-top : 100px">
<%= render 'form' %>
</div>

app/views/appointments/show.html.erb
<div id="team">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class= "container "style = "padding-top: 100px">
          <% Array(@appointment).each do |a|%>
          <div class="col-md-12 col-sm-12 wow fadeIn" data-wow-delay="1.3s">
            <%= image_tag a.professional.photo.url %>
            <%= image_tag a.client.photo.url %>
            <h3><%= a.date.strftime("%d/%m/%Y") %></h3>
            <h1><%= a.name %></h1>
            <h4><%= a.description %></h4>
            <%= link_to "Volver", appointments_path, class:'smoothScroll btn btn-primary wow fadeInUp' %>
          <% end %>
       </div>
      </div>
    </div>
  </div>
</div>