config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, controllers: {
     sessions: 'users/sessions',
     registrations: 'users/registrations',
     :omniauth_callbacks => "users/omniauth_callbacks"
   }
   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self)
   resources :users do
     resources :appointments, except: :index
   end
  resources :appointments, only: :index
  get 'geocontroller/findaddress'
  root to: 'users#index'
  get 'professional/index'
  get 'about/about_us'
  delete '/users/:user_id/appointments/:id', to: 'appointments#destroy', as: 'destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.Admin?
         can :manage, :all
       elsif user.role("Professional")
         can :destroy, Appointment, professional_id: user.id
         can :create, Appointment
         can :read, :all
       else
         can :create, Appointment
         can :read, :all
       end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :client, class_name: 'User'
  belongs_to :professional, class_name: 'User'
  has_many :payments
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :appointment
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
  enum role: [:Admin, :Cliente, :Profesional]
  mount_uploader :photo, ImageUploader
  has_many :client_appointments, class_name: 'Appointment', foreign_key: :client_id, dependent: :destroy
  has_many :professional_appointments, class_name: 'Appointment', foreign_key: :professional_id, dependent: :destroy
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end
  def self.created_by_day
    group_by_day(:created_at).count
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about_us
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to root_url, alert: exception.message }
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo email ocupation phone role address
    latitude longitude])
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def after_sign_up_path_for(resource)
      request.env['omniauth.origin'] || stored_location_for(resource) || edit_user_registration_path(current_user.id)
  end

end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  attr_accessor
  def index
    if current_user.role == 'Profesional'
      @appointments = Appointment.all.where(professional_id: current_user.id)
    elsif current_user.role == 'Cliente'
      @appointments = Appointment.all.where(client_id: current_user.id)
    end

  end

  def show
    @appointment = Appointment.find(params[:id])
    @professional = User.find(params[:user_id])
  end

  def new
    @appointment = Appointment.new
    @user = User.find(params[:user_id])
  end

  def create
    @appointment = Appointment.new(appointments_params)
    @appointment.client_id = current_user.id
    @appointment.professional_id = User.find(params[:user_id]).id

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to user_appointment_path(params[:user_id], @appointment.id), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @appointment.update(appointments_params)
        format.html { redirect_to @appointment, notice: 'Event was successfully updated.'}
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @appointments = Appointment.find(params[:id])
    @appointments.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def appointments_params
    params.require(:appointment).permit(:description, :date, :user_id, :name)
  end
end

app/controllers/geocontroller_controller.rb
# frozen_string_literal: true

class GeocontrollerController < ApplicationController
  def findaddress
    @address = Geocoder.address([params[:latitude], params[:longitude]])
  end
end

app/controllers/professional_controller.rb
class ProfessionalController < ApplicationController
  def index
    @user = User.where(role: 2).all
  end
end

app/controllers/proffesional_controller.rb
class ProffesionalController < ApplicationController
  def index
    @user = User.where(role: 2).all
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @user = User.where(role: 2).last(3)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit;end
  private

  def user_params
    params.require(:user).permit(:name, :photo, :email, :phone, :ocupation, :role, :created_at)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/geocontroller_helper.rb
module GeocontrollerHelper
end

app/helpers/proffesional_helper.rb
module ProffesionalHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-7">
        <p>SOLUCIONES A TU ALCANCE</p>
        <small>HECHO POR ALEX PÉREZ</small>
      </div>
      <div class="col-md-4 col-sm-5">
        <ul class="social-icon">
          <li><a href="#" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="#" class="fa fa-instagram"></a></li>
          <li><a href="#" class="fa fa-pinterest"></a></li>
          <li><a href="#" class="fa fa-google"></a></li>
          <li><a href="#" class="fa fa-github"></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<body data-spy="scroll" data-offset="50" data-target=".navbar-collapse">
  <div class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon icon-bar"></span>
          <span class="icon icon-bar"></span>
          <span class="icon icon-bar"></span>
        </button>
        <a href="<%= new_admin_user_session_path %>" class="navbar-brand"><img src='<%= asset_path 'logo.png' %>' class="img-responsive" alt="logo"></a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li> <%= link_to "HOME", root_path, class:'smoothScroll' %> </li>
          <li><%= link_to "Indice de Usuarios", professional_index_path , class:'smoothScroll' %> </li>
          <li><%= link_to "Tus Citas" , appointments_path, class:'smoothScroll' %></li>
          <% else %>
          <li> <%= link_to "HOME", root_path, class:'smoothScroll' %> </li>
          <% end %>
          <% if user_signed_in? %>
              <li> <%= link_to "Salir", destroy_user_session_path, method: :delete, class:'smoothScroll' %> </li>
            <% else %>
            <li>  <%= link_to "Ingresar", new_user_session_path, class:'smoothScroll' %> </li>
            <li>  <%= link_to "Registrar", new_user_registration_path, class:'smoothScroll' %> </li>
            <% end %>
            <li><%= link_to "QUIENES SOMOS", about_about_us_path, class: 'smoothScroll'%></li>
        </ul>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoFinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/82f5441ef6.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= render 'layouts/navbar' %>
      <%= yield %>
      <%= render 'layouts/footer'%>

  </div>


  </body>
</html>

app/views/shared/_chart.html.erb
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<% my_chart = User.created_by_day %>
<%= bar_chart my_chart %>